version: "3"

services:

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__PROTOCOL=https
      - GITEA__server__SSH_PORT=222
      - GITEA__server__DOMAIN=subdomain.domain.com
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__security__SECRET_KEY=gitea_secret_key
      - GITEA__security__INTERNAL_TOKEN=gitea_internal_token
      - GITEA__log__LEVEL=Info
      - GITEA__log__MODE=console,file
    env_file: .env
    restart: unless-stopped
    networks:
      - inet-gitea
      - net-gitea
    volumes:
      - /home/gitea/.ssh/:/data/git/.ssh
      - ./themes/:/data/gitea/public/css/:ro
      - ./dumps/:/tmp/
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - inet-gitea
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gitea:
    driver: local
  postgres:
    driver: local

networks:
  inet-gitea:
    external: false
  net-gitea:
    external: true
